require File.join(Rails.root.to_s, 'app', 'models', 'customer')
require File.join(Rails.root.to_s, 'app', 'models', 'customer_success')
require File.join(Rails.root.to_s, 'app', 'entities', 'customer')
require File.join(Rails.root.to_s, 'app', 'entities', 'customer_success')
require File.join(Rails.root.to_s, 'app', 'repositories', 'customer', 'memory')
require File.join(Rails.root.to_s, 'app', 'repositories', 'customer_success', 'memory')
require File.join(Rails.root.to_s, 'app', 'repositories', 'customer', 'active_record')
require File.join(Rails.root.to_s, 'app', 'repositories', 'customer_success', 'active_record')
require File.join(Rails.root.to_s, 'app', 'repositories', 'repositories')
require File.join(Rails.root.to_s, 'app', 'use_cases', 'distribute_customer')
require File.join(Rails.root.to_s, 'app', 'use_cases', 'use_cases')
