version: '2'

services:
  db:
    image: 'postgres:9.5'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  web:
    depends_on:
      - db
    build: .
    ports:
      - '8080:3000'
    volumes:
      - '.:/usr/src/app'
volumes:
  postgres:
