version: "2"
services:
  web:
    image: lccezinha/get-started:part-2
    entrypoint: /var/app/entrypoint.sh
    ports:
      - "80:80"
    networks:
      - webnet
    volumes:
      - .:/var/app
networks:
  webnet:
